apiVersion: apps/v1
kind: Deployment
metadata:
  name: agents-ui-deployment
  labels:
    app: agents-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: agents-ui
  template:
    metadata:
      labels:
        app: agents-ui
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/health"
        prometheus.io/port: "80"
    spec:
      containers:
      - name: agents-ui
        image: dalaillama/agents-ui:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        envFrom:
        - configMapRef:
            name: agents-ui-config
