trigger:
  branches:
    include:
      - main  # Trigger on main branch changes
  paths:
    include:
      - 'src/**'
      - 'public/**'
      - 'package.json'
      - 'app.json'
      - 'eas.json'
pool:
  vmImage: 'ubuntu-latest'  # Using Ubuntu as build agent

variables:
  nodeVersion: '16.13.0'  # Use a version compatible with legacy peer dependencies
  projectName: 'dalai-llama'  # Replace with your actual app name

stages:
- stage: Build
  displayName: 'Build and Deploy Expo Web App'
  jobs:
  - job: BuildAndDeploy
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '$(nodeVersion)'
      displayName: 'Install Node.js'

<<<<<<< HEAD
    - script: |
        npm install -g expo-cli@4.12.0
      displayName: 'Install Expo CLI'

    - script: |
        npm install --legacy-peer-deps
      displayName: 'Install dependencies with legacy peer flag'

    - script: |
        npm run build:web
      displayName: 'Build Expo Web'
    
    - task: ArchiveFiles@2
      inputs:
        rootFolderOrFile: 'web-build'
        includeRootFolder: false
        archiveType: 'zip'
        archiveFile: '$(Build.ArtifactStagingDirectory)/$(projectName).zip'
        replaceExistingArchive: true
      displayName: 'Archive Web Build'

    - task: PublishBuildArtifacts@1
      inputs:
        pathtoPublish: '$(Build.ArtifactStagingDirectory)'
        artifactName: 'web-app'
        publishLocation: 'Container'
      displayName: 'Publish Build Artifacts'

- stage: Deploy
  dependsOn: Build
  condition: succeeded()
  jobs:
  - deployment: DeployWebApp
    environment: 'Production'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: AzureWebApp@1
            inputs:
              azureSubscription: 'Microsoft Azure Sponsorship(d6714331-8b1a-434e-9ea6-f62310887e73)'  # Replace with your Azure subscription
              appType: 'webApp'
              appName: '$(projectName)'
              package: '$(Pipeline.Workspace)/web-app/$(projectName).zip'
              deploymentMethod: 'auto'
            displayName: 'Deploy to Azure Web App'
=======
- script: |
    npm install -g expo-cli
    npm install --legacy-peer-deps
  displayName: 'Install dependencies'
>>>>>>> efea554 (Update azure-pipelines.yml)


      