version: '2.4'

services:
  dalai_llama_app:
    build:
      context: .
      args:
        - NODE_ENV=development
    environment:
      - NODE_ENV=development
    tty: true
    ports:
      - '19006:19006'
      - '19001:19001'
      - '19002:19002'
    volumes:
      - ./dalai-llama:/opt/dalai-llama/app:delegated
      - ./dalai-llama/package.json:/opt/dalai-llama/package.json
      - ./dalai-llama/package-lock.json:/opt/dalai-llama/package-lock.json
      - notused:/opt/dalai-llama/app/node_modules
    healthcheck:
      disable: true

volumes:
  notused: