apiVersion: v1
kind: ConfigMap
metadata:
  name: platform-ui-config
  labels:
    app: platform-ui
data:
  APP_NAME: "platform-ui"
  PROM_PUSH_URL: "https://prom.dalaillama.in/api/v1/push"
  API_BASE_URL: "https://api.dalaillama.in"
