apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: platform-ui-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  rules:
  - host: platform-ui.dalaillama.in
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: platform-ui-svc
            port:
              number: 80
  tls:
  - hosts:
    - platform-ui.dalaillama.in
    secretName: platform-ui-tls
