apiVersion: v1
kind: Service
metadata:
  name: platform-ui
  labels:
    app: platform-ui
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 80
    targetPort: 80
  selector:
    app: platform-ui
