apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: platform-ui
  namespace: front-dev
spec:
  hosts:
  - LAPTOP-L2KMRIN8
  gateways:
  - istio-ingress/platform-ui-gateway
  http:
  - route:
    - destination:
        host: platform-ui.front-dev.svc.cluster.local
        port:
          number: 80
