export const PREMIUM_FOOD_TYPOGRAPHY_PRESETS = [
  {
    id: "SWISS_FMCG_SYSTEM",
    name: "Swiss Premium FMCG",
    useFor: "Default system for premium food and chocolate advertising",
    primaryFont: "Inter",
    secondaryFont: "Montserrat",
    primaryWeight: 800,
    secondaryWeight: 500,
    caseRule: "Sentence case for benefits; uppercase only for short product hooks",
    maxLines: 2,
    backgroundStyle: "Matte black or clean image negative space",
    entrance: "Wipe and fade",
    speed: "Measured",
    prompt: "Premium FMCG typography, Swiss editorial grid, bold geometric sans-serif, Inter and Montserrat inspired hierarchy, mixed weights, restrained uppercase, white type over matte black or clean negative space, high contrast, elegant spacing, thin outline boxes, translucent information panels, luxury food advertising, modern DTC grocery campaign.",
  },
  {
    id: "INGREDIENT_EMPHASIS",
    name: "Ingredient Emphasis",
    useFor: "Ingredient truth, provenance, or recipe-quality statements",
    primaryFont: "Inter",
    secondaryFont: "Inter",
    primaryWeight: 800,
    secondaryWeight: 400,
    caseRule: "Sentence case; bold only the ingredient or differentiator",
    maxLines: 2,
    backgroundStyle: "No panel; white type on matte black",
    entrance: "Slide up and fade",
    speed: "Measured",
    prompt: "Clean Swiss-inspired ingredient typography, geometric sans-serif, regular setup line with extra-bold ingredient line, generous spacing, left aligned, white on matte black, premium minimal food advertising.",
  },
  {
    id: "NUTRITION_PANEL",
    name: "Nutrition Information Panel",
    useFor: "Short verified nutrition facts or compact product information",
    primaryFont: "Oswald",
    secondaryFont: "Inter",
    primaryWeight: 700,
    secondaryWeight: 600,
    caseRule: "Compact sentence case; numerals lead",
    maxLines: 3,
    backgroundStyle: "Semi-transparent dark rectangle",
    entrance: "Fade",
    speed: "Quick",
    prompt: "Condensed sans-serif nutrition typography, bold white numerals and compact supporting copy inside a translucent charcoal panel, tight but readable leading, modern premium packaging-label hierarchy.",
  },
  {
    id: "CLEAN_INGREDIENT_STATEMENT",
    name: "Clean Ingredient Statement",
    useFor: "Verified no-additive or no-preservative statements",
    primaryFont: "Inter",
    secondaryFont: "Inter",
    primaryWeight: 750,
    secondaryWeight: 450,
    caseRule: "Sentence case, one statement per line",
    maxLines: 2,
    backgroundStyle: "No panel; editorial white type",
    entrance: "Fade",
    speed: "Measured",
    prompt: "Minimal Helvetica-style editorial food typography, bold headline with regular supporting text, left aligned, white on solid black or strong negative space, simple premium composition.",
  },
  {
    id: "PRODUCT_NAME_BADGE",
    name: "Premium Product Badge",
    useFor: "Product or flavour name reveal",
    primaryFont: "Bebas Neue",
    secondaryFont: "Inter",
    primaryWeight: 700,
    secondaryWeight: 500,
    caseRule: "Uppercase product name; carefully tracked",
    maxLines: 2,
    backgroundStyle: "Thin rectangular outline, transparent fill",
    entrance: "Zoom and fade",
    speed: "Slow",
    prompt: "Luxury product-name typography, uppercase condensed sans-serif, precise tracking, white text enclosed by a thin white rectangular keyline, elegant gourmet packaging aesthetic.",
  },
  {
    id: "BENEFIT_EMPHASIS",
    name: "Benefit Emphasis",
    useFor: "Verified benefit copy with one emphasized keyword",
    primaryFont: "DM Sans",
    secondaryFont: "DM Sans",
    primaryWeight: 800,
    secondaryWeight: 500,
    caseRule: "Sentence case; bold the key benefit only",
    maxLines: 2,
    backgroundStyle: "No panel; white on matte black",
    entrance: "Slide up and fade",
    speed: "Measured",
    prompt: "Editorial sans-serif benefit statement, mixed weights with restrained bold emphasis on one verified keyword, white on matte black, premium grocery branding, clean hierarchy and generous breathing room.",
  },
  {
    id: "HERO_PRODUCT_TITLE",
    name: "Hero Product Title",
    useFor: "Opening hook or hero product reveal",
    primaryFont: "Montserrat",
    secondaryFont: "Playfair Display",
    primaryWeight: 900,
    secondaryWeight: 600,
    caseRule: "Two short uppercase lines with one accent word",
    maxLines: 3,
    backgroundStyle: "Open composition with one approved accent color",
    entrance: "Wipe and fade",
    speed: "Quick",
    prompt: "Oversized geometric sans-serif hero title, mixed scale, one approved accent-color keyword, strong editorial grid, bold premium DTC food branding, modern composition with protected product negative space.",
  },
  {
    id: "PASTEL_HIGHLIGHT",
    name: "Pastel Highlight Label",
    useFor: "Flavour, variant, or editorial annotation",
    primaryFont: "Oswald",
    secondaryFont: "Inter",
    primaryWeight: 700,
    secondaryWeight: 500,
    caseRule: "Short title case label",
    maxLines: 1,
    backgroundStyle: "Approved pastel highlight strip with dark text",
    entrance: "Slide up and fade",
    speed: "Quick",
    prompt: "Bold condensed dark typography on a restrained pastel highlight strip, editorial magazine label, premium modern food campaign, minimal layout and crisp padding.",
  },
  {
    id: "EDITORIAL_TAG",
    name: "Editorial Campaign Tag",
    useFor: "Campaign line or closing thought",
    primaryFont: "Poppins",
    secondaryFont: "Inter",
    primaryWeight: 700,
    secondaryWeight: 500,
    caseRule: "Natural sentence case",
    maxLines: 2,
    backgroundStyle: "Soft pastel tag box with dark text",
    entrance: "Fade",
    speed: "Slow",
    prompt: "Modern bold sans-serif campaign line in a soft pastel tag box, natural uppercase and lowercase mix, premium grocery editorial art direction, generous padding and clean hierarchy.",
  },
];

export const DEFAULT_TYPOGRAPHY_PRESET_ID = "SWISS_FMCG_SYSTEM";

export function typographyPresetById(id) {
  return PREMIUM_FOOD_TYPOGRAPHY_PRESETS.find((preset) => preset.id === id)
    || PREMIUM_FOOD_TYPOGRAPHY_PRESETS[0];
}
