# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - dalai-llama

on:
  push:
    branches:
      - v2
  workflow_dispatch:
env:
  NODE_VERSION: '22.x'
  WEB_BUILD_OUTPUT: 'web-build'  

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'

      - name: Install Dependencies
        run: |
          npm install -g expo-cli
          npm install --legacy-peer-deps
        
      - name: Build Web Version
        run: |
          expo install @expo/webpack-config
          npx expo export:web


      - name: Zip artifact for deployment
        run: zip release.zip ./* -r

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Unzip artifact for deployment
        run: unzip release.zip
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_7F5D9E36B5844015A64F89A3B71B018F }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_B75BAC3E83D944C58EF23244406D2F00 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_4A739C9E3C3C4977912B4ACFB6E01BE7 }}

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'dalai-llama'
          slot-name: 'Production'
          package: .
          
